package NotePadApp;

/**
* NotePadApp/NotePadHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NotePad.idl
* 27 но€бр€ 2019 г. 15:20:36 MSK
*/

public final class NotePadHolder implements org.omg.CORBA.portable.Streamable
{
  public NotePadApp.NotePad value = null;

  public NotePadHolder ()
  {
  }

  public NotePadHolder (NotePadApp.NotePad initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NotePadApp.NotePadHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NotePadApp.NotePadHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NotePadApp.NotePadHelper.type ();
  }

}
