package NotePadApp;


/**
* NotePadApp/NoteListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NotePad.idl
* 27 но€бр€ 2019 г. 15:20:36 MSK
*/

public final class NoteListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public NoteListHolder ()
  {
  }

  public NoteListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NotePadApp.NoteListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NotePadApp.NoteListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NotePadApp.NoteListHelper.type ();
  }

}
