package NotePadApp;


/**
* NotePadApp/NotePad.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from NotePad.idl
* 27 но€бр€ 2019 г. 15:20:36 MSK
*/

public interface NotePad extends NotePadOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface NotePad
